# SPDX-FileCopyrightText: Copyright (c) 2024 Intel Corporation
#
# SPDX-License-Identifier: BSD-3-Clause
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tiber-broadcast-suite-tx
  namespace: default
data:
  node.json: |
    {
      "logging_level": 0,
      "http_port": 90,
      "label": "intel-broadcast-suite",
      "senders": ["v"],
      "senders_count": [1],
      "receivers": ["v"],
      "receivers_count": [0],
      "device_tags": {
        "pipeline": ["tx-sender"]
      },
      "function": "tx-sender",
      "gpu_hw_acceleration": "none",
      "domain": "default.svc.cluster.local",
      "ffmpeg_grpc_server_address": "tiber-broadcast-suite-tx.default.svc.cluster.local",
      "ffmpeg_grpc_server_port": "50051",
      "sender_payload_type": 112,
      "sender": [{
        "stream_payload": {
          "video": {
            "frame_width": 1960,
            "frame_height": 1080,
            "frame_rate": { "numerator": 60, "denominator": 1 },
            "pixel_format": "yuv422p10le",
            "video_type": "rawvideo"
          },
          "audio": {
            "channels": 2,
            "sample_rate": 48000,
            "format": "pcm_s24be",
            "packet_time": "1ms"
          }
        },
        "stream_type": {
          "mcm": {
            "conn_type": "st2110",
            "transport": "st2110-20",
            "urn": "NULL",
            "transport_pixel_format": "yuv422p10le"
          }
        }
      }],
      "receiver": [{
        "stream_payload": {
          "video": {
            "frame_width": 1920,
            "frame_height": 1080,
            "frame_rate": { "numerator": 60, "denominator": 1 },
            "pixel_format": "yuv422p10le",
            "video_type": "rawvideo"
          },
          "audio": {
            "channels": 2,
            "sample_rate": 48000,
            "format": "pcm_s24be",
            "packet_time": "1ms"
          }
        },
        "stream_type": {
          "file": {
            "path": "/root",
            "filename": "1920x1080p10le_1.yuv"
          }
        }
      }]
    }

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tiber-broadcast-suite-tx
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tiber-broadcast-suite-tx
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: tiber-broadcast-suite-tx
    spec:
      containers:
      - args:
        - config/intel-node-rx.json
        env:
        - name: http_proxy
        - name: https_proxy
        - name: VFIO_PORT_TX
          value: 0000:ca:11.0
        image: tiber-broadcast-suite-nmos-node:latest
        imagePullPolicy: IfNotPresent
        name: tiber-broadcast-suite-nmos-node
        ports:
        - containerPort: 90
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 250m
            memory: 64Mi
        securityContext:
          allowPrivilegeEscalation: false
          seccompProfile:
            type: RuntimeDefault
          capabilities:
            drop:
            - ALL
        readinessProbe:
          httpGet:
            path: /
            port: 50051
            host: tiber-broadcast-suite-tx.default.svc.cluster.local
          initialDelaySeconds: 5
          periodSeconds: 10
        volumeMounts:
        - mountPath: /home/config
          name: config
      - args:
        - localhost
        - "50051"
        env:
        - name: http_proxy
        - name: https_proxy
        - name: VFIO_PORT_TX
          value: "${VFIO_PORT_TX}"
        image: tiber-broadcast-suite:latest
        imagePullPolicy: IfNotPresent
        name: tiber-broadcast-suite
        ports:
        - containerPort: 50051
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 250m
            memory: 64Mi
        securityContext:
          capabilities:
            add:
            - ALL
          privileged: true
          runAsUser: 0
        volumeMounts:
        - mountPath: /videos
          name: videos
        - mountPath: /usr/local/lib/x86_64-linux-gnu/dri
          name: dri
        - mountPath: /tmp/kahawai_lcore.lock
          name: kahawai-lock
        - mountPath: /dev/null
          name: dev-null
        - mountPath: /tmp/hugepages
          name: hugepages-tmp
        - mountPath: /hugepages
          name: hugepages
        - mountPath: /var/run/imtl
          name: imtl
        - mountPath: /dev/shm
          name: shm
      volumes:
      - hostPath:
          path: /root/DEMO_NMOS/move/nmos/nmos-cpp/Development/nmos-cpp-node/
          type: ""
        name: videos
      - hostPath:
          path: /usr/lib/x86_64-linux-gnu/dri
          type: ""
        name: dri
      - hostPath:
          path: /tmp/kahawai_lcore.lock
          type: ""
        name: kahawai-lock
      - hostPath:
          path: /dev/null
          type: ""
        name: dev-null
      - hostPath:
          path: /tmp/hugepages
          type: ""
        name: hugepages-tmp
      - hostPath:
          path: /hugepages
          type: ""
        name: hugepages
      - hostPath:
          path: /var/run/imtl
          type: ""
        name: imtl
      - hostPath:
          path: /dev/shm
          type: ""
        name: shm
      - hostPath:
          path: /dev/vfio
          type: ""
        name: vfio
      - configMap:
          defaultMode: 420
          name: tiber-broadcast-suite-tx
        name: config

---
apiVersion: v1
kind: Service
metadata:
  name: tiber-broadcast-suite-tx
  namespace: default
spec:
  type: NodePort
  selector:
    app: tiber-broadcast-suite-tx
  ports:
  - protocol: TCP
    port: 90
    targetPort: 90
    name: tiber-broadcast-suite-tx-node-port-http
    nodePort: 30084
  - protocol: TCP
    port: 50051
    targetPort: 50051
    name: grpc-client-to-ffmpeg
    nodePort: 30051